name: flutter_state_manager
description: A simple state management library for Flutter applications.
version: 1.0.0
homepage: https://github.com/your_username/flutter_state_manager
repository: https://github.com/your_username/flutter_state_manager
issue_tracker: https://github.com/your_username/flutter_state_manager/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_state_manager
      ios:
        pluginClass: FlutterStateManagerPlugin

# Đảm bảo thêm thông tin về license
flutter:
  uses-material-design: true
