name: custom_state_management
description: A simple state management library for Flutter applications.
version: 1.0.0
homepage: https://github.com/baotran310702/Custom-State-Management
repository: https://github.com/baotran310702/Custom-State-Management
issue_tracker: https://github.com/baotran310702/Custom-State-Management/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
